### ISSUE TITLE
建议取消页面转码的注释，并添加ignore，忽略非法字符

### ISSUE THREAD

**Issue by sugarguo** [howie6879/ruia#10]
gb2312 编码的网页会存在问题

```python
#request.py

import chardet

#line 121
#res_data = await resp.text()
content = await resp.read()
charset = chardet.detect(content)
res_data = content.decode(charset['encoding'], 'ignore')

```

**Comment by howie6879** [comment]
@sugarguo 

你好，为什么取消是因为这是一个轻量的框架，不想过多依赖第三方库，对于编码问题，你可以:

- 利用read()方法获取字节进行解码
- 或者我另外开一个关于编码的ruia插件 ruia-cchardet
- 我这边提供一个编码参数，你那边使用的时候，比如gb2312，直接传encoding = `gb2312`，这边帮你解码

你觉得哪种方案比较好
