### ISSUE TITLE
在start()方法传入自定义关键字参数在实例方法中无法获取到参数

### ISSUE THREAD

**Issue by YellowDong** [howie6879/ruia#105]
你好 请问我的用法哪里出了问题么 我获取不到我传进来的关键字参数
`

class MySpider(Spider):

     start_urls = ["http://xxxxxxxxx"]
    async def parse(self, response):
        print(self.kwargs)
`

`MySpider.start(key="hello", word="world")`

**Comment by howie6879** [comment]
你把这些`key="hello", word="world"`定义在类的属性里面比较好

**Comment by YellowDong** [comment]
爬虫启动的时候我需要动态传入参数初始化spider 如果写在类属性里初始化的时候不是也是通过start方法初始化吗么 我看到start方法好像是支持自定义关键字参数的呀

**Comment by howie6879** [comment]
目前定在了类属性下面，我更新了个版本，你下载最新的吧：

```shell
pip install git+https://github.com/howie6879/ruia
```

```python
class TestSpider:
         ....
         print(self.spider_kwargs)
```

**Comment by YellowDong** [comment]
thanks
