### ISSUE TITLE
定义的Field类对json数据结构的抽取

### ISSUE THREAD

**Issue by YellowDong** [howie6879/ruia#106]
目前好像只看到给定html或者etree.Element,或者给定url返回的html进行css,xpath等抽取，对返回是json结构数据怎么定义Item类的field属性呢

`
MyItem(Item):
    url = xxField() 
`

**Comment by howie6879** [comment]
json还要解析干嘛，天然已经解析好了

**Comment by YellowDong** [comment]
只是想用Item类统一管理想要的字段再入库或者缓存

**Comment by howie6879** [comment]
item返回的结果是字典
返回的json解析后也是字典
一样的，所以这块你只能自己想办法

**Comment by YellowDong** [comment]
还发现了个问题 params参数在请求里面接收不到
`
url = "https://www.baidu.com"
params = {"kw": "ruia"}
yield Request(url, params=params, callback=self.parse)
`
请求的url并不是https://www.baidu.com?kw=ruia

**Comment by howie6879** [comment]
你是怎么判断不是的呢？

**Comment by YellowDong** [comment]
`import aiohttp
import asyncio

from ruia import Request

params = {"kw": "ruia", "some": "target"}

# ruia demo
request = Request("https://www.baidu.com", params=params)
response = asyncio.get_event_loop().run_until_complete(request.fetch())
print(response.url)  # https://www.baidu.com

# aiohttp demo
async def fetch():
    async with aiohttp.ClientSession() as session:
        response = await session.get("https://www.baidu.com", params=params)
        print(response.url)  # https://www.baidu.com/?kw=ruia&some=target

asyncio.get_event_loop().run_until_complete(fetch())`

**Comment by howie6879** [comment]
明白你的意思，实际上请求带上了参数，没有显示，你安装最新版，解决了这个问题哈
