### ISSUE TITLE
请问可以用beautifulsoup来代替默认的解析器吗？

### ISSUE THREAD

**Issue by synodriver** [howie6879/ruia#113]
看了一下框架，似乎还是需要生成Item对象，不然无法入库

**Comment by howie6879** [comment]
不支持bs，不过可以用bs扩展field类进行这块的支持

**Comment by synodriver** [comment]
谢谢，另外我也写了一个扩展的下载器，调用aria2多线程下载的，可以结合起来，这样就可以摆脱下载大文件时候的gil限制https://github.com/synodriver/aioaria2，这个项目也许用的上

**Comment by nqzhang** [comment]
主页图片好评
