### ISSUE TITLE
文档方便详细点吗?

### ISSUE THREAD

**Issue by lyg4795** [howie6879/ruia#115]
我看到豆瓣的例子中,有request_config aiohttp_kwargs 两个设置,但是我在文档中一直没有看到这两个的具体说明,topic/request里面并没有具体的解释.
还有Spider.start里面也会带参数,但是提供的例子中并没有使用这些参数,所以对这些参数的正确使用方法会有疑问.
如果有具体的例子和说明可以增加对应的链接,方便理解
另外,爬虫中往往会使用代理,专门有个例子来描述这一块的内容会不会更好点

**Comment by howie6879** [comment]
好建议，你有兴趣丰富下文档吗哈哈

**Comment by lyg4795** [comment]
> 好建议，你有兴趣丰富下文档吗哈哈

我也不知道这些参数的含义啊

**Comment by howie6879** [comment]
如果你有兴趣完善的话，加我文档里面的微信，不清楚我微信和你说，哈哈

**Comment by howie6879** [comment]
@lyg4795 老哥，要完善文档吗

**Comment by lyg4795** [comment]
@howie6879 之前群里问的那个在parse_item里面添加yeild会导致不同步的问题,没搞定,觉得自己手写代码,先不用框架了
