### ISSUE TITLE
用pip安装bug

### ISSUE THREAD

**Issue by heyaug** [howie6879/ruia#116]
![image](https://user-images.githubusercontent.com/57477226/89852349-37d37f00-dbc1-11ea-9312-418b66c3039e.png)
setup.py第28行是不是要加utf-8
![image](https://user-images.githubusercontent.com/57477226/89852485-8719af80-dbc1-11ea-958c-6280c47046e9.png)

**Comment by howie6879** [comment]
@heyaug 你是在pycharm的终端安装吗？

**Comment by howie6879** [comment]
首先肯定是编码问题哈，确实要加一个，你的安装问题是否已经解决？

**Comment by heyaug** [comment]
我是用pip，加编码就可以安装了
