### ISSUE TITLE
Add trackback to logger.error() for spider

### ISSUE THREAD

**Issue by ts709** [howie6879/ruia#119]
Thanks for the wonderful light-weighted yet powerful package!

In my use of the package, one thing I hope to improve is I cannot tell where it occurs if an exception/error happens. For example, I got two errors in my log:

```
INFO  Request <GET: https://x-x-x.com/page1.htm>
INFO  Request <GET: https://x-x-x.com/page2.htm>
ERROR Ruia list index out of range
ERROR Ruia list index out of range
INFO  Request <GET: https://x-x-x.com/page3.htm>
INFO  Request <GET: https://x-x-x.com/page4.htm>
```

As my spider and items code is complex, I cannot even guess which line of my code is causing the "list index out of range" error, so I have to set breakpoints and step through my code. It becomes difficult when the error happens later in a queue of many urls.

I have tried to set the logging level to DEBUG and apparently it doesn't help. 

I looked into the Ruia code and my reading is that line 204-205 of https://github.com/howie6879/ruia/blob/master/ruia/spider.py only captures the str message of an exception and nothing else for the log. I tried to add the traceback with these two lines, but nothing is actually captured. I assume that the use of async functions and callback in ruia disables sys.exc_info call to get the traceback.

```
  tb = sys.exc_info()
  self.logger.debug(e.with_traceback(tb[2]))
```

I then followed the suggestion in this stackoverflow Q/A (https://stackoverflow.com/a/45640638/688693) and created a  decorator to hopefully log traceback for functions in my code.

```
from ruia.utils import get_logger
from functools import wraps

logger = get_logger()

def log_error(result, name='Ruia'):
    logger = get_logger(name)
    exc_info  = result.exc_info()
    if exc_info:
        logger.debug('EXCEPTION %s', exc_info)

def handle_exception(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        future = fn(*args, **kwargs)
        future.add_done_callback(log_error)
        return future
    return wrapper
```

But when I use the handle_exception decorator in my code (for example, with spider.parse() and the classmethod Item._parse_html()), I am getting an error in the log: "ERROR Ruia 'async_generator' object has no attribute 'add_done_callback'". My understanding is that the add_done_callback method is only available for asyncio.Future, not async_generator. I am very new to async programming and I am stuck here. I appreciate any help/pointer you can give me. Thanks!

I see that you have an open issue for a Ruia plugin for debugging (#32), but there is few details how it can/may be implemented. I am willing to help if I can figure out how it may work.

**Comment by howie6879** [comment]
Sorry I'm a bit busy lately, but I will get back to you on the weekend

**Comment by howie6879** [comment]
Hi @ts709 : 

Please update to v0.7.0 and see if that solves your problem!

**Comment by ts709** [comment]
It does! I didn't realize the solution is as simple as that. Thank you so much!

**Comment by howie6879** [comment]
Hi @ts709 : 

I'm glad to solve your problem, can I close this issue?

**Comment by ts709** [comment]
yes, please!
