### ISSUE TITLE
Extension for batch POST requests with different payload data

### ISSUE THREAD

**Issue by peiyaoli** [howie6879/ruia#121]
Maybe we could extends the POST requests with different data with fixed URL instead of batch URLs without request data?

**Comment by howie6879** [comment]
Hi @peiyaoli :

What problems did you encounter in using Ruia before you came up with this idea?

**Comment by peiyaoli** [comment]
Hi, @howie6879 

In my project, I need to extract millions of data point with POST request and request data format is in XML. 
However, API provider limit the data point I can get for one batch, for instance, 500 point. Then I have to split this million data points into thousands of batch payloads, each with 500 point. And send these hundreds of request to one URL asynchoronously or in parallel.

**Comment by howie6879** [comment]
![image](https://user-images.githubusercontent.com/17047388/96678596-9e84ce00-13a4-11eb-864e-6e191232b8c0.png)

we can talk about your situation in more detail on WeChat.

**Comment by peiyaoli** [comment]
sure, added, let's discuss on WeChat
