### ISSUE TITLE
AttributeError: 'Response' object has no attribute 'html'

### ISSUE THREAD

**Issue by xiaoniaoyouhuajiang** [howie6879/ruia#130]
在官方文档里看到Response对象有html的属性：
![image](https://user-images.githubusercontent.com/23737972/108582936-27bb0a00-7371-11eb-8c10-39be55af87d3.png)
但是在源码里并未看到，测试代码时也遇到了如题所示的错误：
![image](https://user-images.githubusercontent.com/23737972/108582973-5a650280-7371-11eb-9107-192192b6ded0.png)

**Comment by howie6879** [comment]
抱歉，新版本移除了忘了更新文档，现在这样获取：

```shell
html = await response.text()
```

**Comment by xiaoniaoyouhuajiang** [comment]
感谢~

**Comment by howie6879** [comment]
> 感谢~

我看你好像在终端实验ruia，可以用以下ruia的终端调试工具：https://github.com/python-ruia/ruia-shell

**Comment by xiaoniaoyouhuajiang** [comment]
> > 感谢~
> 
> 我看你好像在终端实验ruia，可以用下ruia的终端调试工具：https://github.com/python-ruia/ruia-shell

好的。我有看你的一个ruia示例项目：https://github.com/howie6879/anan作为ruia的学习材料，不过该项目基于ruia0.5.5，现在已经无法运行了，请问有意更新一下该项目嘛？

**Comment by howie6879** [comment]
那个现在没时间弄了。。不过ruia下面的example下面很多例子，这个例子你也可以参考：https://github.com/howie6879/monkey

**Comment by howie6879** [comment]
@xiaoniaoyouhuajiang 是否还有问题，如果没有，我将关闭Issue
