### ISSUE TITLE
Is it possible to use SOCKS5 proxy?

### ISSUE THREAD

**Issue by Leezj9671** [howie6879/ruia#131]
It seems only support http/https proxy.

**Comment by Leezj9671** [comment]
Ok, I got it. Will create a PR.
```
@middleware.request
async def request_proxy(spider_ins, request: Request):
    """request using proxy example"""
    # SOCKS5 proxy using aiohttp_socks
    # Check docs in https://pypi.org/project/aiohttp-socks/
    from aiohttp import ClientSession
    from aiohttp_socks import ProxyConnector
    # connector = ProxyConnector.from_url('socks5://username:password@127.0.0.1:1080')
    connector = ProxyConnector.from_url('socks5://127.0.0.1:9999')
    request.request_session = ClientSession(connector=connector)
    request.close_request_session = True
```

**Comment by howie6879** [comment]
It’s a great implementation, here’s another way to do it, just for reference:

```python
import aiofiles

from aiohttp import ClientSession
from aiohttp_socks import ProxyConnector

from ruia import AttrField, Item, Spider, TextField


class HackerNewsItem(Item):
    target_item = TextField(css_select="tr.athing")
    title = TextField(css_select="a.storylink")
    url = AttrField(css_select="a.storylink", attr="href")

    async def clean_title(self, value):
        return value.strip()


class SocksSpider(Spider):
    socks_url = "socks5://127.0.0.1:1086"

    def __init__(self, **kwargs):
        super(SocksSpider, self).__init__(**kwargs)
        connector = ProxyConnector.from_url(self.socks_url) if self.socks_url else None
        self.request_session = ClientSession(connector=connector)


class HackerNewsSpider(SocksSpider):
    start_urls = [
        "https://news.ycombinator.com/news?p=1",
        "https://news.ycombinator.com/news?p=2",
    ]
    concurrency = 10

    async def parse(self, response):
        async for item in HackerNewsItem.get_items(html=await response.text()):
            yield item

    async def process_item(self, item: HackerNewsItem):
        async with aiofiles.open("./hacker_news.txt", "a") as f:
            self.logger.info(item)
            await f.write(str(item.title) + "\n")


if __name__ == "__main__":
    HackerNewsSpider.start(middleware=None)
```

**Comment by howie6879** [comment]
> Will create a PR.

I think it is better to implement this feature as a plug-in, what do you think ?

**Comment by Leezj9671** [comment]
> I think it is better to implement this feature as a plug-in, what do you think ?

Cool, that will be a great feature.

**Comment by howie6879** [comment]
> Cool, that will be a great feature.

Are you interested in this  job? --> [ruia-proxy](https://github.com/python-ruia/ruia-proxy)

We can provide such api:

```python
from ruia_proxy import ProxySpider

class HackerNewsSpider(SocksSpider):
    start_urls = [
        "https://news.ycombinator.com/news?p=1",
        "https://news.ycombinator.com/news?p=2",
    ]
    concurrency = 10
    socks_url = "socks5://127.0.0.1:1086"

    async def parse(self, response):
        pass

```

**Comment by Leezj9671** [comment]
Why not code like above, but create a new project? Using proxies should be a crawler feature.

**Comment by howie6879** [comment]
> Why not code like above, but create a new project? Using proxies should be a crawler feature.

Good question, because the realization of this function also needs to download a third-party library`aiohttp_socks`, for Ruia users, not everyone needs this function,.

So we can't import `aiohttp_socks` into Ruia, encapsulate a plug-in and let developers who need it by themselves downloading is a better solution. 

Do you have any suggestions?

**Comment by Leezj9671** [comment]
There is no need to create a new project specifically to do this because
library aiohttp_socks did it well.

My advice is add my example code in docs which already can fully show how
to use socks5 proxy.

howie.hu ***@***.***>于2021年3月23日 周二下午8:49写道：

**Comment by howie6879** [comment]
Of course it is possible to do so. 

I think socks is just a small feature. I hope to add more features, such as providing free proxy pools and more proxy type support, such as https, etc.
