### ISSUE TITLE
python3.9 remove asyncio.Task.all_tasks()

### ISSUE THREAD

**Issue by happyli0826** [howie6879/ruia#136]
python3.9     部分方法更改，可加入版本判断
spider.py

源函数
async def _cancel_tasks(self):
        tasks = []
        for task in asyncio.Task.all_tasks():
            if task is not asyncio.tasks.Task.current_task():
                tasks.append(task)
                task.cancel()
        await asyncio.gather(*tasks, return_exceptions=True)

3.9修改后
  async def _cancel_tasks(self):
      tasks = []
      for task in asyncio.all_tasks():
          if task is not asyncio.current_task():
              tasks.append(task)
              task.cancel()
      await asyncio.gather(*tasks, return_exceptions=True)

**Comment by howie6879** [comment]
@happyli0826 谢谢反馈，方便提个PR？

**Comment by howie6879** [comment]
@happyli0826 感谢反馈

是不是你用的ruia版本不是最新的？最新版已经做了适配

**Comment by happyli0826** [comment]
是的，版本是旧的，打扰了，不好意思

发自我的iPhone

**Comment by howie6879** [comment]
不会啊，有任何问题欢迎反馈

happyli0826 ***@***.***> 于2021年4月17日周六 下午2:15写道：
