### ISSUE TITLE
HtmlField?

### ISSUE THREAD

**Issue by panhaoyu** [howie6879/ruia#17]
hello, I want to get the raw html code, so I write another field, named HtmlField.

```python3
import ruia.field

class HtmlField(ruia.field._LxmlElementField):
    def _parse_element(self, element):
        return etree.tostring(element)
```

Is it useful to add it to ruia? Or I'll write an tutorial of adding custom fields.

I don't know if there is a better implementation with current version.

**Comment by howie6879** [comment]
@panhaoyu Hi:
I think it's useful, you can add it to Ruia.
BTW Can you add a regular extract？

**Comment by panhaoyu** [comment]
I don't know how to implement such a method.
In scrapy, it is like a parsing stream, we use `response.css('.tag').re('tag\d+')`.
But in ruia, I have no idea.

In fact, I think scrapy's API is very friendly, but it's too heavy

**Comment by panhaoyu** [comment]
If you regard it as a clean method, perhaps write it in `clean_field(self, value)` is also ok?

Or if you want better performance, we can inherit a subclass from `BaseField` named `ReField`.

**Comment by panhaoyu** [comment]
But I think defining in the item class is more friendly,
for we can create all selectors in a single way,
it will not cause any confusion.

If implement the API like scrapy, that means another system of selector.
Ruia has a declarative programming API,
I think it's more clear than scrapy's API.

In the parsing method in scrapy, in order to try my best to split parsing html and  saving data, I always do such a thing:

```python

class Spider(scrapy.Spider):
    ...
    def parse(self, response):
        title = response.css('.title').extract_first()
        href = response.css('.href').extract_first()
        tags = response.css('.href').extract_first()
        cover_image_url = response.css('.cover').extract_first()
        item = peewee.SomeItem()
        item.title = title
        item.href = href
        item.tags = tags
        item.cover_image_url = cover_image_url
```

It makes the parse function very very long and unreadable.

Scrapy has pipelines to solve this problem.
However, I think Ruia's solution is better.
We can explicitly seperate selectors and data processings easily.

For the pagination example you referred above, define another class is okay:

```
class Pagination(Item):
    next_url = ruia.AttrField(css_select='.next', attr='href')
    previous_url = ruia.AttrField(css_select='.previous', attr='href')
```

**Comment by howie6879** [comment]
You are right , just add a subclass named `ReField` is enough
