### ISSUE TITLE
New logo wanted for Ruia

### ISSUE THREAD

**Issue by howie6879** [howie6879/ruia#18]
Need a logo meaning "Light and Fast crawler", I think the logo looks like a running girl.

**Comment by mirzazulfan** [comment]
Hi @howie6879 what about this?
![ruia](https://user-images.githubusercontent.com/36124339/51961238-a42ed780-248e-11e9-8ef7-232e3b93291c.png)
Best regard.

**Comment by howie6879** [comment]
Hi @mirzazulfan : 
Thanks for your logo, Can you explain the meaning of the logo?

**Comment by howie6879** [comment]
@mirzazulfan Hi：
I am so glad you can help me design the logo

Ruia need a logo meaning "Light and Fast crawler", I think the logo looks like a running girl.

**Comment by howie6879** [comment]
> Thanks for your response @howie6879 , I make it like a crawler. If you need something else I will make it.

Hi, are you doing this?

**Comment by howie6879** [comment]
> Thanks for your response @howie6879 , I make it like a crawler. If you need something else I will make it.

Hi, is this thing still going on?

**Comment by LouisYZK** [comment]
Why you named it ruia?

**Comment by howie6879** [comment]
> Why you named it ruia?

To my love ~ a lovely girl

**Comment by howie6879** [comment]
![image](https://user-images.githubusercontent.com/17047388/52680124-54faa380-2f72-11e9-80b3-b259e58e568b.png)

Some ideas about the logo：
- Left: parallel lines can evoke async streams
- Right: Like a girl on the run

**Comment by mirzazulfan** [comment]
Hi @howie6879 Sorry, did not see the notification. How about this? If you need anything change i'll fix it.
![ruia 2](https://user-images.githubusercontent.com/36124339/52696857-b0448a00-2fa2-11e9-80b4-d5f7d5e6bfdf.png)

**Comment by howie6879** [comment]
@mirzazulfan 
So beautiful, i think this is a good one, btw, can there be more changes in color?
What do you think? have any ideas for improvement?

**Comment by howie6879** [comment]
> Hi @howie6879 Sorry, did not see the notification. How about this? If you need anything change i'll fix it.
> ![ruia 2](https://user-images.githubusercontent.com/36124339/52696857-b0448a00-2fa2-11e9-80b4-d5f7d5e6bfdf.png)

I have already invited you. can you submit the logo to this project? [ruia-assets](https://github.com/ruia-plugins/ruia-assets)

**Comment by mirzazulfan** [comment]
Im glad you liked it. Sure, what color and size do you prefer? :)

**Comment by howie6879** [comment]
> Im glad you liked it. Sure, what color and size do you prefer? :)

What about red？

**Comment by mirzazulfan** [comment]
I'll send all files tomorrow. :) 
![red](https://user-images.githubusercontent.com/36124339/52703518-1801d180-2fb1-11e9-96db-140131264ab3.png)

**Comment by howie6879** [comment]
> I'll send all files tomorrow. :)
> ![red](https://user-images.githubusercontent.com/36124339/52703518-1801d180-2fb1-11e9-96db-140131264ab3.png)

Thank you very much, so beautiful.

**Comment by howie6879** [comment]
![image](https://user-images.githubusercontent.com/17047388/52766068-f8c27d00-3060-11e9-9139-0d991cf91fe2.png)
It seems that there is no circular logo in the project.

**Comment by mirzazulfan** [comment]
I've uploaded all of them. also you can download all files [here](https://drive.google.com/drive/folders/17yuk7FeoQ03oDU8WeTiIKaqrJcvwJbG1). If you need anything change in the future, please let me know. :). Thanks @howie6879 im glad to help your project.

**Comment by howie6879** [comment]
@mirzazulfan 

Great job,  thank you so much
