### ISSUE TITLE
Type checking for start_urls

### ISSUE THREAD

**Issue by panhaoyu** [howie6879/ruia#37]
```python
    def __init__(self, middleware=None, loop=None, is_async_start=False):
        if not self.start_urls or not isinstance(self.start_urls, list):
            raise ValueError("Spider must have a param named start_urls, eg: start_urls = ['https://www.github.com']")
```
This type checking should check for collections.Iterable,

Here's an instance:

I want to crawl a website, like hacker news.
Pages are orderd by number,
so I write such a start_urls:

```
start_urls = (f'https://some.site.com/{index}' for index in range(1, 100000))
```

Then it took a long time to start crawling.

**Comment by panhaoyu** [comment]
#39

**Comment by howie6879** [comment]
> a producer-consumer model

Ruia is using a producer-consumer model in spider.py

I have noticed this problems, i'll fixed this issue.
