### ISSUE TITLE
Documentation translate Chinese to English

### ISSUE THREAD

**Issue by howie6879** [howie6879/ruia#4]
https://github.com/howie6879/aspider/blob/master/docs/en/README.md

**Comment by muzico425** [comment]
你好 spider.py文件 155行 那句是啥用途

**Comment by panhaoyu** [comment]
Done, with my poor English skills.

**Comment by howie6879** [comment]
Closed https://github.com/howie6879/ruia/pull/12

**Comment by howie6879** [comment]
> Done, with my poor English skills.

Hi @panhaoyu 

Thanks for your PR

But you seem to have missed this [article](https://github.com/howie6879/ruia/blob/master/docs/en/first_steps/plugins.md)

**Comment by panhaoyu** [comment]
I noticed, so I made another pr...
