### ISSUE TITLE
如何在item里面定义接收API返回的JSON结构

### ISSUE THREAD

**Issue by chenlei9907** [howie6879/ruia#49]
如何在item里面定义接收API返回的JSON结构

如果访问的是API url， API返回json， 在item里面如何用使用呢？

**Comment by chenlei9907** [comment]
好像不支持 HTTPS代理， 如何才能使用HTTPS代理呢？

**Comment by howie6879** [comment]
> 好像不支持 HTTPS代理， 如何才能使用HTTPS代理呢？

ruia的异步请求基于aiohttp，你的问题可参考 https://github.com/aio-libs/aiohttp/issues/2245 进行解决
