### ISSUE TITLE
target_item expected error

### ISSUE THREAD

**Issue by misterpilou** [howie6879/ruia#58]
I wrote a spider, the code is there https://codeshare.io/5NQXr1.
I just want to retrieve the links in one Item element, I've got a link = AttrField(css_select='a', attr='href'), but when it's called in a async for, i've got a target_item expected error. In the examples you have done in the repo, when calling item with get_items(), they all got a clean_link or clean_title async method. But i don't think it's the issue. Also response.html contains links.

**Comment by howie6879** [comment]
Hi @misterpilou 

![image](https://user-images.githubusercontent.com/17047388/52911364-dab58080-32dd-11e9-811f-cf07942087a5.png)
In this line you should use` await RecipeUrl.get_item(html=response.html)` instead

More details click [here](https://python-ruia.org/en/apis/item.html)

**Comment by howie6879** [comment]
About this line: 
![image](https://user-images.githubusercontent.com/17047388/52911424-8bbc1b00-32de-11e9-9e12-99e9005f081a.png)
```python
async def clean_link(self, link):
        return link
```

**Comment by misterpilou** [comment]
okay thanks you very much, i will test that now

**Comment by misterpilou** [comment]
Yes it work, i need to debug others parts. I will work a bit with ruia, i think i will have others questions. Doing it in issues is imo irrelevant, is there a chat or any others ways to process? Would you be interested to have a new contributor?

**Comment by howie6879** [comment]
Hi @misterpilou : 

I am so glad to hear that you want to be a contributor to the ruia project, hope to see your PR Soon.

BTW, we can talk about ruia in our chat romm, click [here](https://gitter.im/howie6879_ruia/community)
