### ISSUE TITLE
Scrape multiple websites & save results in a database [Question]

### ISSUE THREAD

**Issue by hubitor** [howie6879/ruia#59]
What are the possible options for scraping multiple websites e.g. through a list or a file and saving the results in a database?

**Comment by howie6879** [comment]
Can you post a details question?
May be this script will help you :https://github.com/howie6879/ruia/blob/master/examples/topics_examples/hacker_news_spider.py

**Comment by howie6879** [comment]
If you want to save the results in mongodb
there is a example:

click [here](https://github.com/python-ruia/ruia-motor/blob/master/example/hn_motor.py)

**Comment by hubitor** [comment]
I've never used asyncio or any of the asynchronous libraries in python before and from what I've read, the normal libraries cannot be used with asyncio, that's why I'm asking. I don't have some code yet I could post. I'm just investigating the options. 

> Can you post a details question?
> May be this script will help you

What do you mean by this? Would it be possible to put some thousand URLs in the start_urls list?
Would it be possible or make sense to combine Celery with ruia?

So there is currently support only for mongodb?

**Comment by howie6879** [comment]
If there are too many links crawled, I suggest putting them in the parse function for crawling.

Motor_ruia is a plugin that I wrote, for other databases, just use a supported third-party library,for example, mysql can consider using [aiomysql](https://github.com/aio-libs/aiomysql),more lib you can click [here](https://github.com/aio-libs)

Shouldn't it be up to the user whether it makes sense to combine Celery with Ruia? do you think it makes sense to have the combination of celery and Asyncio?

**Comment by howie6879** [comment]
If you are interested in asynchronous, I think this is a good choice.😄

**Comment by hubitor** [comment]
OK, Thanks. I'll look into it.
