### ISSUE TITLE
How can I add a proxies-rotator into the middleware?

### ISSUE THREAD

**Issue by marcusau** [howie6879/ruia#60]
Hi, Thanks for your awesome contribution for this wonderful open library.

Just one question. Besides random ua, I also wanna add my own proxy-rotator into the ruia spider. 

I have searched the py.files of requests and ua but yet to sort out the input location of my proxy rotator.

Would you tell me where i can plug-in that into the module?

**Comment by howie6879** [comment]
Hi @marcusau : 

Thanks for your support of Ruia.

For your problem, you can write code like this：

```python
middleware = Middleware()

@middleware.request
async def print_on_request(spider_ins, request):
    request.kwargs.update({'proxy': 'your proxy'})
```

**Comment by marcusau** [comment]
> Hi @marcusau :
> 
> Thanks for your support of Ruia.
> 
> For your problem, you can write code like this：
> 
> ```python
> middleware = Middleware()
> 
> @middleware.request
> async def print_on_request(spider_ins, request):
>     request.kwargs.update({'proxy': 'your proxy'})
> ```

Thanks a lot.

Your library is quite useful and efficient. I express my sincere appreciation for your contribution.

Just one follow-up question,

I suppose we should put our proxy rotator in the ruia-ua module, right?

For the proxy format storing in {'proxy': ' xxxx' }, the format is 'http:\\proxy_numbers' or just like the format of request.get which is ' { 'http': http:\\proxy_numbers, 'https': http:\\proxy_numbers}

Please instruct. Thanks a lot

**Comment by howie6879** [comment]
Hi @marcusau : 

the format is `{"proxy": "http://0.0.0.0:1080"}`

Ruia's Request is based on aiohttp, more details you can click  [here](https://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support)
