### ISSUE TITLE
How can I scrap the text contents from a list of urls extracted from parse function in spider?

### ISSUE THREAD

**Issue by marcusau** [howie6879/ruia#61]
from ruia import AttrField, TextField, Item
    from ruia_pyppeteer import PyppeteerSpider as Spider
    from ruia_pyppeteer import PyppeteerRequest as Request
    from ruia_ua import middleware

    domain='caixin'
    domain_page = 'http://www.caixin.com/search/scroll/index.jsp'

    class frame_Item(Item):
        target_item = TextField(css_select='body > div.indexBody > div.news > div.news_content')  
        publish_times = TextField(css_select='dl > dd > span', many=True)
        headline_texts = TextField(css_select='dl> dd > a', many=True)  
        news_urls = AttrField(attr='href',css_select='dl> dd > a',many=True) 

    class texts_Item(Item):
        target_item = TextField(css_select='r"/body > div.comMain > div.conlf > #the_content"') 
        news_texts = TextField(css_select='"div.content > div.textbox" ', many=True)

    class caixin_realtime_Spider(Spider):
        start_urls = [domain_page]
        concurrency = 5

        async def parse(self, response):
            async for item in frame_Item.get_items(html=response.html):
                yield item

        async def process_item(self, item:frame_Item):
            for url in item.news_urls:
                yield Request(url, callback=self.parse_item) 

        async def parse_item(self, response):
            async for item in caixin_news_Item.get_items(html=response.html):
                 print(item.news_texts)

 
    def run():
        print('Scraping ', domain,  domain_page)
        caixin_realtime_Spider.start(middleware=middleware)       

    if __name__ == '__main__':
        run()
        db.close()

The thing is ... I only have the follow result:

Scraping  caixin 財新網 http://www.caixin.com/search/scroll/index.jsp
[2019:03:05 17:14:57] WARNING Spider  Ruia tried to use loop.add_signal_handler but it is not implemented on this platform.
[2019:03:05 17:14:57] WARNING Spider  Ruia tried to use loop.add_signal_handler but it is not implemented on this platform.
[2019:03:05 17:14:57] INFO  Spider  Spider started!
[2019:03:05 17:14:57] INFO  Spider  Worker started: 1947326139520
[2019:03:05 17:14:57] INFO  Spider  Worker started: 1947326139656
[I:pyppeteer.launcher] Browser listening on: ws://127.0.0.1:54430/devtools/browser/b72b7efd-7b6b-4353-a7d4-acec7a7f02b4
[I:pyppeteer.launcher] terminate chrome process...
[2019:03:05 17:15:00] ERROR Spider  object async_generator can't be used in 'await' expression
[2019:03:05 17:15:00] INFO  Spider  Stopping spider: Ruia
[2019:03:05 17:15:00] INFO  Spider  Total requests: 1
[2019:03:05 17:15:00] INFO  Spider  Time usage: 0:00:02.876312
[2019:03:05 17:15:00] INFO  Spider  Spider finished!
[2019:03:05 17:15:00] ERROR asyncio Task was destroyed but it is pending!
task: <Task pending coro=<async_generator_athrow()>>

**Comment by howie6879** [comment]
> [2019:03:05 17:15:00] ERROR Spider object async_generator can't be used in 'await' expression

You should change your code:

```python
from ruia import AttrField, TextField, Item
from ruia_pyppeteer import PyppeteerSpider as Spider
from ruia_pyppeteer import PyppeteerRequest as Request
from ruia_ua import middleware

domain='caixin'
domain_page = 'http://www.caixin.com/search/scroll/index.jsp'

class frame_Item(Item):
    target_item = TextField(css_select='body > div.indexBody > div.news > div.news_content')  
    publish_times = TextField(css_select='dl > dd > span', many=True)
    headline_texts = TextField(css_select='dl> dd > a', many=True)  
    news_urls = AttrField(attr='href',css_select='dl> dd > a',many=True) 


class texts_Item(Item):
    target_item = TextField(css_select='r"/body > div.comMain > div.conlf > #the_content"') 
    news_texts = TextField(css_select='"div.content > div.textbox" ', many=True)


class caixin_realtime_Spider(Spider):
    start_urls = [domain_page]
    concurrency = 5

    async def parse(self, response):
        async for item in frame_Item.get_items(html=response.html):
            for url in item.news_urls:
                yield Request(url, callback=self.parse_item)

    async def parse_item(self, response):
        async for item in caixin_news_Item.get_items(html=response.html):
             print(item.news_texts)


def run():
    print('Scraping ', domain,  domain_page)
    caixin_realtime_Spider.start(middleware=middleware)       


if __name__ == '__main__':
    run()
    db.close()

```
