### ISSUE TITLE
建议和疑惑

### ISSUE THREAD

**Issue by youyiqin** [howie6879/ruia#67]
能否在创建自己的Item类的同时，对AttrField中获取href的时候，获取到的是绝对地址。这样就可以省下写一个clean函数的时间了。（逃）

**Comment by howie6879** [comment]
你好：
谢谢你的建议，但是这个需求并不是能普遍到所有的开发者上，有的开发者就是要path咋搞，所以这部分就开发者自己处理一下，urlparse用起来

如果你想去除重复性劳动，可以自己写个插件😏

**Comment by youyiqin** [comment]
有道理。
