### ISSUE TITLE
ruia 似乎没有使用一个队列来维护所有的任务，如果有突发情况停止了爬虫，下次重新启动就需要重新开始一遍

### ISSUE THREAD

**Issue by DeemoASCII** [howie6879/ruia#68]
因为之前使用 scrapy 比较多，但是 scrapy 是基于 twisted 的框架，偶然发现了 ruia 是基于 aiohttp 和 asyncio 的异步框架，可是看完文档之后发现并没有像 scrapy 一样的一个 scheduler，如果爬虫突然停止之后是不是就没法儿从上次停止的地方继续爬取，如果量很大的话从头再来一次就要做很多重复性工作了，不知道开发者有没有想过添加这个功能，使用了 scheduler 之后还能够对任务进行比较简单的去重。

**Comment by howie6879** [comment]
你好，感谢你的建议

现在ruia是检测到队列里面有请求就进行消费，我没有详细了解过scrapy的scheduler，我会了解完再看看，这功能也是我之前就想加的

如果你对这块了解比较多，也欢迎提交PR，个人是觉得可以以插件的形式实现这个功能

**Comment by Snailwicked** [comment]
@howie6879 target_item是用来干嘛的啊!跟其他的css_select是一样的，少了还报错

**Comment by howie6879** [comment]
@Snailwicked 文档写的挺清楚的：https://docs.python-ruia.org/en/apis/item.html

**Comment by triangle959** [comment]
有没有考虑用redis或者其他消息队列进行队列持久化，让爬虫中断后再重新向队列取任务

**Comment by howie6879** [comment]
> 有没有考虑用redis或者其他消息队列进行队列持久化，让爬虫中断后再重新向队列取任务

有的  可以通过插件的形式实现

**Comment by howie6879** [comment]
我构建了 [ruia-cache](https://github.com/python-ruia/ruia-cache)来对爬虫进行缓存，目前发现`aiohttp`不支持序列化，已向官方提了issue [5378](https://github.com/aio-libs/aiohttp/issues/5378)

I built ruia-cache to cache the URL. I found that `aiohttp` does not support serialization. I have submitted issue  [5378](https://github.com/aio-libs/aiohttp/issues/5378) to the official.

**Comment by howie6879** [comment]
Done! [ruia-cache](https://github.com/python-ruia/ruia-cache)

ruia-cache will automatically cache the captured URL to prevent the second request to the target web page:
