### ISSUE TITLE
process_item is only call when the callback_result is an Item

### ISSUE THREAD

**Issue by hiancdtrsnm** [howie6879/ruia#75]
This is a question of curiosity. Why limit the process_item for item resulting.
I think that must be called on every result.

the lines are the 199-202 of spider.py

```python
                elif isinstance(callback_result, Item):
                    # Process target item
                    await self.process_item(callback_result)
```

**Comment by howie6879** [comment]
I think it's a good way to implement some custom plugins for Ruia.

For example: [ruia-motor](https://github.com/python-ruia/ruia-motor)
