### ISSUE TITLE
question: Is there any option for continuous scraping

### ISSUE THREAD

**Issue by iAnanich** [howie6879/ruia#76]
Scrapy (an old but time-proven twisted-based framework) has Frontera - a library for managing scalable clusters of scrapers, where URLs can be added to a queue dynamically by some management-node and actual scraping performed by another.
So my question is about is there any mechanism for performing similar things with ruia? (cause I was about to write my own implementation of similar thing)

**Comment by howie6879** [comment]
Hi @iAnanich :
Sorry for my slow reply, Because these days are National Day in China.
You can easily develop third-party plug-ins based on Ruia, the core is to realize URLs management.

**Comment by iAnanich** [comment]
Great, thank you!

**Comment by iAnanich** [comment]
@howie6879 Does `ruia` support async iterator as spider's `start_urls` attribute? If it isn't, I see only one way of getting new URLs on the go - add some code that will be executed after each parsing completed. It is a bit counter-intuitive (after using Scrapy) that I can't yield request objects from `parse` function.

**Comment by howie6879** [comment]
@iAnanich Sorry, I don't quite understand your description. Can you explain your problem with the code?

**Comment by iAnanich** [comment]
In Scrapy you can provide `start_urls` as a list, or define `start_urls` method which will yield `Request` object. And so, I could easily make an iterator that will create Requуst objects based on some external queue.
But in Ruia examples, I have seen `start_urls` only as an attribute with static value.
Another way of somehow making new requests is by adding at the end of `parse` method (or other methods chained in parsing) code that will make asynс requests, as shown in examples.
```from ruia import Spider
class MySpider(Spider):
    async def parse(self, response):
        next_response = await self.request(f'{response.url}/next')
        yield self.parse_next_page(next_response, metadata='nothing')
    async def parse_next_page(self, response, metadata):
        print(response.html)```

**Comment by howie6879** [comment]
In Ruia, `start_urls` is a necessary attribute.

there is a `process_start_urls` method in the `spider.py`, you can process start URL before `parse` func.

Can this method help you?
