### ISSUE TITLE
能不能简单说下为什么Spider类不需要新建实例，直接空降了个start就能运行了

### ISSUE THREAD

**Issue by ElderWanng** [howie6879/ruia#77]

**Comment by howie6879** [comment]
@classmethod方法

**Comment by ElderWanng** [comment]
谢谢，，，恶补了好多知识。。。学到好多。。。顺便问下有没有一个推荐的代码阅读顺序？

**Comment by howie6879** [comment]
客气了，能学到东西就好，你可以看我这篇介绍博客：https://www.howie6879.cn/post/2019/03_how_to_build_a_web_scraping_framework_with_python/

看完了可以考虑写个基于ruia的插件
