### ISSUE TITLE
target_item is expected error

### ISSUE THREAD

**Issue by r3v1** [howie6879/ruia#79]
I have the next piece of code, taken (and modified) from [Spider Control](https://docs.python-ruia.org/en/tutorials/spider.html):

```
import re

import aiofiles
from ruia import TextField, Item, Spider


class Player(Item):
    # target_item = TextField(xpath_select='//div[@class="info"]/div[@class="meta bp3-text-overflow-ellipsis"]')
    player_id = TextField(xpath_select='//div[@class="info"]/h1')
    info = TextField(xpath_select='//div[@class="info"]/div[@class="meta bp3-text-overflow-ellipsis"]')

    async def clean_player_id(self, value):
        return int(re.search(r'[0-9]{2,7}', value).group())

    async def clean_info(self, value):
        return re.search(r'([A-Z](.\ [A-Z])?[a-z]+ *)+', value).group()


class SoFifa(Spider):
    start_urls = [
        "https://sofifa.com/player/239053/federico-valverde/200012/",
        "https://sofifa.com/player/197928/jonathan-bond/200012/",
        "https://sofifa.com/player/248243/eduardo-camavinga/200012/"
    ]

    async def parse(self, response):
        async for item in Player.get_items(html=response.html):
            yield item

    async def process_item(self, item: Player):
        print(f"{item.info} (ID: {item.player_id})")

        """Ruia build-in method"""
        async with aiofiles.open('./players.txt', 'a') as f:
            await f.write(f"{item.info} (ID: {item.player_id})" + '\n')


if __name__ == '__main__':
    SoFifa.start()
```

And when running, I receive the next error:

> [2019:11:27 20:22:42] INFO  Spider  Spider started!
> [2019:11:27 20:22:42] INFO  Spider  Worker started: 140065780358320
> [2019:11:27 20:22:42] INFO  Spider  Worker started: 140065780358496
> [2019:11:27 20:22:42] INFO  Request <GET: https://sofifa.com/player/239053/federico-valverde/200012/>
> [2019:11:27 20:22:42] INFO  Request <GET: https://sofifa.com/player/197928/jonathan-bond/200012/>
> [2019:11:27 20:22:42] INFO  Request <GET: https://sofifa.com/player/248243/eduardo-camavinga/200012/>
> [2019:11:27 20:22:43] ERROR Spider  target_item is expected
> [2019:11:27 20:22:43] ERROR Spider  target_item is expected
> [2019:11:27 20:22:43] ERROR Spider  target_item is expected
> [2019:11:27 20:22:43] INFO  Spider  Stopping spider: Ruia
> [2019:11:27 20:22:43] INFO  Spider  Total requests: 3
> [2019:11:27 20:22:43] INFO  Spider  Time usage: 0:00:00.726866
> [2019:11:27 20:22:43] INFO  Spider  Spider finished!

But when I remove the comment on 

`target_item = TextField(xpath_select='//div[@class="info"]/div[@class="meta bp3-text-overflow-ellipsis"]')`

the error dissapear. Why is `target_item` required or what I'm misunderstanding?

Thanks

**Comment by howie6879** [comment]
Hi @r3v1 :
Maybe this doc can help you: https://python-ruia.org/en/tutorials/item.html

**Comment by r3v1** [comment]
Thanks, it helps.
