### ISSUE TITLE
`text()` in xpath selector causes an error

### ISSUE THREAD

**Issue by abmyii** [howie6879/ruia#83]
I assume this is because of using `TextField` rather than another field. Which is more ideal? The error caused by line 120:
https://github.com/howie6879/ruia/blob/8a91c0129d38efd8fcd3bee10b78f694a1c37213/ruia/field.py#L120
```
'lxml.etree._ElementUnicodeResult' object has no attribute 'itertext'
```
I was thinking that `itertext` shouldn't be used if the element has that type to avoid that error. That way `text()` will work fine.

**Comment by howie6879** [comment]
This may need to be evaluated on a case-by-case basis. Can you post the detail code to take a look

**Comment by abmyii** [comment]
```
text = TextField(xpath_select='.//article/div[@style="text-align: justify;"]/text()', many=True)
```

Gives the error:
```
'lxml.etree._ElementUnicodeResult' object has no attribute 'itertext'
```

**Comment by howie6879** [comment]
This is because the child element you extract contains a type other than text

**Comment by abmyii** [comment]
It doesn't. When I remove `/text()` from the xpath selector it works. This is because `ruia` expects an element - not a string result (which `/text()` selector returns). The solution is:
```python
if type(element) is etree._ElementUnicodeResult:
    strings = [node.strip() for node in element]
else:
	strings = [node.strip() for node in element.itertext()]
```
I will probably PR this after #85 is merged as they will conflict otherwise.

**Comment by howie6879** [comment]
Sorry, I remembered it incorrectly. The correct usage is not to add / text, because TextField is to extract text. If you think this will cause misunderstanding, it can be compatible with both cases.

**Comment by abmyii** [comment]
I think it's best if it can handle all cases of xpaths for flexibility. I'll add it and submit a PR.

**Comment by abmyii** [comment]
BTW I really appreciate your fast responses and PR merges - thank you very much!
