### ISSUE TITLE
No field for capturing raw LXML elements

### ISSUE THREAD

**Issue by abmyii** [howie6879/ruia#88]
I need to capture the raw LXML element(s) and process them before converting to text. Right now I have created a very simple new field (not sure if best way to implement):
```
class ElementField(_LxmlElementField):

    def _parse_element(self, element):
        return element
```
I think this should be part of ruia core, not an extension.

**Comment by howie6879** [comment]
I think so, you can submit a PR for this problem.

abmyii <notifications@github.com>于2020年1月11日 周六上午6:33写道：

**Comment by abmyii** [comment]
Will do, thanks!
May I ask why you decided to make a new library rather than use already existing ones - scrapy particularly? My reason why I looked for another library was that I found scrapy too slow. The increase I found was 4x!

**Comment by howie6879** [comment]
As the description says, I want to build an  async Python 3.6+ web scraping micro-framework based on asyncio, 

But it cannot be denied that Scrapy is the current mainstream framework, so Ruia also considers following some Scrapy APIs

**Comment by abmyii** [comment]
I see, thanks for answering my question!

> As the description says, I want to build an async Python 3.6+ web scraping micro-framework based on asyncio,

You've done a great job!

**Comment by howie6879** [comment]
Thank you, 
I wish more people were involved in Ruia's development just like you.
