### ISSUE TITLE
Default shoudn't be enclosed in list

### ISSUE THREAD

**Issue by abmyii** [howie6879/ruia#92]
https://github.com/howie6879/ruia/blob/b8aa61d34f5f4b8511b77630ab9086bd3c4e7bec/ruia/field.py#L79

This leads to confusing unexpected outputs like:
```
TextField(css_select="div.brand b", default=[], many=True)

> [[]]
```

**Comment by howie6879** [comment]
Hi：

Thanks for your issue, but I think it is not a bug

When `many` is set to True, FieldClass must return a list object, which has nothing to do with the `default` parameter

**Comment by abmyii** [comment]
Why must it return a list? I tested my change all tests passed. The problem with having `[[]]` is that functions with `for i in ...` start iterating even though there is no actual result. Is there any other way of getting only `[]` when default is used?

**Comment by howie6879** [comment]
you can set `default` = ''

> way of getting only `[]` when default is used?

**Comment by howie6879** [comment]
> Why must it return a list?

Because when setting many, the developer knows that there are multiple corresponding values for this field, so most developers will perform a for loop on such a result. If the corresponding value cannot be obtained, the str type is returned. This is a disaster for the crawler script

**Comment by abmyii** [comment]
> you can set `default` = ''
> 
> > way of getting only `[]` when default is used?

This will return `[""]` which is a list that is not empty.

How about changing:
https://github.com/abmyii/ruia/blob/b1231c804e19bfcef06f0431da3307a1e9de6500/ruia/field.py#L82

To:
```
results = self.default if type(self.default) == list else [self.default]
```

That way if `TextField(css_select="div.brand b", default=[], many=True)` then `[]` is only returned whereas if `TextField(css_select="div.brand b", default="...", many=True)` then `["..."]` is returned?

**Comment by abmyii** [comment]
Updated my branch.
