### ISSUE TITLE
Documentation about IgnoreThisItem

### ISSUE THREAD

**Issue by panhaoyu** [howie6879/ruia#94]
Hi my friend. I'm making a spider today, and I couldn't find the function in the documentation. However, I find it in the source code. 

```
class CityItem(ruia.Item):
    target_item = ruia.TextField(css_select='body > table:nth-of-type(4) td')
    url = ruia.AttrField(attr='href', css_select='a')
    name = ruia.TextField(css_select='a')

    async def clean_name(self, value):
        raise ruia.exceptions.IgnoreThisItem
```
I have a small suggestion, that we should add `IgnoreThisItem` to global namespace of ruia, instead of `ruia.exceptions.IgnoreThisItem`.

I'll write the docs in a few days.

I think write it [here](https://docs.python-ruia.org/en/topics/item_data_cleaning.html) is ok.

**Comment by howie6879** [comment]
Hi, friend @panhaoyu :

Long-time no sees, no problem, just do what you want.

**Comment by panhaoyu** [comment]
![image](https://user-images.githubusercontent.com/23495987/72587017-bb303900-392e-11ea-997b-fe2362d17bfb.png)

Perhaps here should be `continue`, instead of setting an attribute.

**Comment by howie6879** [comment]
私聊
