### ISSUE TITLE
从第一个例子开始，就报错了。。。然后我仿照着去爬别的网站，也会报错。

### ISSUE THREAD

**Issue by YuanQingLe** [howie6879/ruia#98]
![3VM`WO(0~K8~U9U 2L8_5}I](https://user-images.githubusercontent.com/46965669/74097141-ad439180-4b43-11ea-9690-6e1200ce6c83.png)

这是复制例子的。

![TLM{JIS}BAF{RM18@_}UX3H](https://user-images.githubusercontent.com/46965669/74097140-aa48a100-4b43-11ea-9ee8-fe1b04eb3309.png)

这是我自己写的一个。

**Comment by howie6879** [comment]
第一个例子，因为你没翻墙
第二个例子，你代码写的有问题
你可以使用这个例子 https://raw.githubusercontent.com/howie6879/ruia/master/examples/simple_spider/douban_spider.py

**Comment by YuanQingLe** [comment]
> 
> 
> 第一个例子，因为你没翻墙
> 第二个例子，你代码写的有问题
> 你可以使用这个例子 https://raw.githubusercontent.com/howie6879/ruia/master/examples/simple_spider/douban_spider.py

谢谢，你发的这个例子我可以用，我研究研究。不过我开了vpn呀，用浏览器可以访问例子那个网址，为啥用python就访问不到了。

**Comment by h1code2** [comment]
@YuanQingLe 可尝试把翻墙代理设置成全局试试
